version: "3.8"

services:
  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=techtalksdb
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
  techtalks-be:
    container_name: "techtalks-be"
    depends_on:
      - mysqldb
    build: ./
    restart: on-failure
    env_file: ./.env
    ports:
      - "8081:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/techtalksdb?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",        
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
  techtalks-fe:
    image:  tpragaserbatic/techtalks-fe:latest
    container_name: "techtalks-fe"
    ports:
      - "3001:3000"
    depends_on:
      - techtalks-be
volumes:
  db: